config/routes.rb
Rails.application.routes.draw do
  
  
 
  
  resources :genres
  resource :sessions,only: [:new,:create,:destroy]
  resources :users
  get 'create_admin/:id' => 'users#create_admin', as: :create_admin
  get 'remove_admin/:id' => 'users#remove_admin', as: :remove_admin
  root 'movies#index'
  get 'books#index'=> 'books#index', as: :root1
  delete '/movies/:movie_id/favorites/:id' => 'favorites#destroy', as: :movie_favorite
  resources :books
  resources :movies  do
     resources :reviews
     resources :favorites
   end
  # get 'movies'=>'movies#index', as: :index
  # get 'movies/new'=>"movies#new"
  # get 'movies/:id'=>'movies#show', as: :movie
  # get 'movies/:id/edit'=>'movies#edit', as: "edit_movie"
  # patch 'movies/:id'=>'movies#update'	

end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many_attached :uploads
  has_many :reviews,dependent: :destroy
  has_many :favorites,dependent: :destroy
  has_many :fans, through: :favorites, source: :user

  has_many :characterizations
  has_many :genres, through: :characterizations
  validates :title, presence: true
    validates :released_on, presence: true
    validates :duration, presence: true
    validates :description, length: { minimum: 25 }
    validates :total_gross, :numericality => { :greater_than_or_equal_to => 0 }
    # validates :image_file_name, allow_blank: true,format:{
    #     with: /\w+\.(gif|jpg|png)\z/i,
    #     message: "must reference a GIF, JPG, or PNG "
    # }
    RATINGS = %w(G PG PG-13 R NC-17)
  def flop?
    total_gross<50000000
  end
  def self.released
    where("released_on <?",Time.now).order(released_on: :desc)
  end

  def average_stars
    reviews.average(:stars)
  end

  def self.recent_reviews(movie)
    movie.reviews.order(updated_at: :desc).limit(2)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :require_signin, except:[:index,:show]
  before_action :require_admin, except:[:index,:show]
  def index
    @movies=Movie.released
    end
  def show
    @movie=Movie.find(params[:id])
    @fans=@movie.fans
    if current_user
      @current_favorite=current_user.favorites.find_by(movie_id: @movie.id)
    end
    @movie_genres=@movie.genres
  end

  def edit
    @movie=Movie.find(params[:id])
  end

  def update
    @movie=Movie.find(params[:id])
    if @movie.update(movie_params)
      flash[:notice]="successfully updated!!"
       redirect_to root_path
    else
        render :edit
      end
  end

  def new
    @movie=Movie.new
  end

  def create
    @movie=Movie.create(movie_params)
    if @movie.save
      flash[:notice]="successfully inserted!!"
      redirect_to movie_path(@movie)
    else
      render :new
    end
  end

  def destroy
    @movie=Movie.find(params[:id]).delete
    redirect_to movies_path(@movie),notice: "One movie is deleted!!"
  end

  private
    def movie_params
      params.require(:movie).permit!
    end
end

app/helpers/movies_helper.rb
module MoviesHelper
	def formate_total_gross(movie)
		if movie.flop?
			#"<strong>Flop</strong>".html_safe
			 content_tag(:strong, 'Flop!')
		else
			content_tag(:strong, 'Hit!')
		end
	end
	
	
	# def image_for(movie)
	# 		    if movie.image_file_name.blank?
 #      image_tag('placeholder.png')
 #    else
 #      image_tag(movie.image_file_name)
 #    end
 
			# img=movie.image_file_name
		# if File.exist?("Rails.root/'app'/'assets'/'images'/#{img}")
		# 	image_tag(movie.image_file_name)
		# else
		# 	image_tag 'placeholder.png'
		# end
	# end
end

app/views/movies/_form.html.erb
<%= render 'shared/errors', object: @movie%>


<%= form_for @movie do |f| %>
<center>

  <table>
    <tr>
      <td>
        <%= f.label:Title %></td>
        <td><%= f.text_field:title, :autofocus=>true %>
      </td>
    </tr>
    <tr>
      <td>
        <%= f.label:Rating %></td>
        <td>
        <%= f.select :rating, Movie::RATINGS, prompt: "Pick one" %>
      </td>
    </tr>
    <tr>
      <td>
        <%= f.label:Total_gross %></td>
        <td>
        <%= f.number_field:total_gross, :required=>true%>
      </td>
    </tr>
    <tr>
      <td>
        <%= f.label:Description %></td>
        <td>
        <%= f.text_area:description %>
      </td>
    </tr>
    <tr>
      <td>
        <%= f.label:Released_on %></td>
        <td>
        <%= f.date_field:released_on %>
      </td>
    </tr>
    <tr>
      <td>
        <%= f.label:Cast %></td>
        <td>
        <%= f.text_field:cast %>
      </td>
    </tr>
    <tr>
      <td>
        <%= f.label:Director %></td>
        <td>
        <%= f.text_field:director %>
      </td>
    </tr>
    <tr>
      <td>
        <%= f.label :Duration %></td>
        <td>
        <%= f.text_field :duration %>
      </td>
    </tr>
    <tr>
      <td>
        <%= f.label:genres %>
      </td>
      <td>
          <%= f.label :genres %>
          <span style="display: block;" ><%= f.collection_check_boxes(:genre_ids, Genre.all, :id, :name) %></span>
      </td>
    </tr>
    <tr>
      <td>
        <%= f.label :Image %>
      </td>
      <td>
        <%= f.file_field :uploads, multiple: true %>
      </td>
    </tr>

    <tr><td></td><td> <%= link_to "Cancel", movies_path, class: 'btn btn-primary' %><%= f.submit%> </td> </tr>
  </table>
</center>
<%end%>

app/views/movies/_sidebar.html.erb
<div class="sidenav">
  <%= link_to("List All","/movies")%> 
  <%= link_to("Edit",edit_movie_path(@movie))%> 
  <%= link_to("Delete",movie_path(@movie), method: :delete, data:{confirm:"Are you sure"})%>
</div>

app/views/movies/edit.html.erb
<h1>Update Movie Details Here!</h1>
<%= content_for :page_title, "Edit "%>
<%= render 'form'%>

app/views/movies/index.html.erb
<h1><%= pluralize(@movies.count,'Movie')%></h1>
<%= link_to("Add movie",new_movie_path)%><br>
<div class="container">
  <div class="row">
    <div class="col-md-12">
<table class="table table-inverse" >
	<tr> 
	<thead >
		<th>#</th> 
		<th>Title</th>
		<th>Rating</th> 
		<th>Total_gross</th>
		<th>Description</th> 
		<th>Release Date</th>
		<th>Director</th> 
		<% if current_user && current_user.admin?%>
		<th>Edit</th>
		<th>Delete</th>
		<%end%>
	</thead>
</tr>
	<%count=1 %>
	<%@movies.each do |movie|%>
	<tr>
		<td><%= count%></td>
		<td><%= link_to(movie.title,movie_path(movie.id))%> </td>
		<td><%= movie.rating%></td>
		<td><%= formate_total_gross(movie)%></td>
		<td><%= truncate(movie.description,length:29,separator:' ')%></td>
		<td><%= time_ago_in_words(movie.released_on)%> <i><%= movie.released_on.strftime("%B %e, %Y")%></i></td>
		<td><%= movie.director%></td>
		<% if current_user && current_user.admin?%>
		<td><%= link_to("Edit",edit_movie_path(movie.id),  class: "btn btn-primary"  )%></td>
		<td><%= link_to("Delete",movie_path(movie),  class: "btn btn-danger"  , method: :delete, data:{confirm:"Are you sure"})%></td>
		<%end%>
	</tr>
	<%count+=1%>
	<%end%>
</table>
</div>
</div>
</div>

	

		 |
		
		

app/views/movies/new.html.erb
<center>
<h1 style="background-color: #52a6bf">Insert New Movie Here!</h1>
</center>
<%= content_for :page_title, "New "%>
<%= render 'form'%>

app/views/movies/show.html.erb
<div class="main">
  <span style="float: right;"><td><%= link_to("write reviews",new_movie_review_path(@movie))%></span><br>
  <div class="row">
    <div class="col-lg-6">
      <table class="table">
        <tr>
          <td>NAME:</td>
          <td><%= @movie.title%></td>
        </tr>
        <tr>
          <td>Rating:</td>
          <td><%= @movie.rating%></td>
        </tr>
        <tr>
          <td>Total_gross:</td>
          <td><%= @movie.total_gross%></td>
        </tr>
        <tr>
          <td>Description:</td>
          <td><%= @movie.description%></td>
        </tr>
        <tr>
          <td>Released date:</td>
          <td><%= @movie.released_on%></td>
        </tr>
        <tr>
          <td>Cost:</td>
          <td><%= @movie.cast%></td>
        </tr>
          <td>Director:</td>
          <td><%= @movie.director%></td>
        </tr>
        <tr>
          <td>Duration:</td>
          <td><%= @movie.duration%></td>
        </tr>
        <tr>
          <td>Stars:</td>
          <td><%= format_average_stars(@movie)%></td>
        </tr>
        <tr>
          <td>Fans:</td>
          <td><%= pluralize(@fans.count,'fan')%></td>
        </tr>
        <tr>
          <td>Reviews:</td>
          <td><% Movie.recent_reviews(@movie).each do |r|%>
              <%=r.comment%>
            <%end%>
            <%= link_to("All Reviews",movie_reviews_path(@movie) )%>
          </td>
        </tr>
        <tr>
          <td>Genres:</td>
          <td>
            <% @movie_genres.each do |g|%>
              <%=g.name%>
            <%end%>
          </td>
        </tr>
      </table>
    <% if current_user %>
      <div class="favorites">
        <%= render 'favorites/favorites' %>
        <% if !@current_favorite %>
          <%= button_to 'Fave', movie_favorites_path(@movie), :class => 'button fave', remote: true %>
        <%else%>
          <%= button_to 'UnFave',movie_favorite_path(movie_id: @movie.id, id: @current_favorite), :class => 'button fave',method: :delete %>
        <%end%>
      </div>
    <%end%>
  </div>
  <div class="col-lg-6">
    <% @movie.uploads.each do |file| %>
      <%= image_tag url_for(file), class:"img-size" %></div>
    <% end %>
  </div>
</div>