config/routes.rb
Rails.application.routes.draw do
  
  
 
  
  resources :genres
  resource :sessions,only: [:new,:create,:destroy]
  resources :users
  get 'create_admin/:id' => 'users#create_admin', as: :create_admin
  get 'remove_admin/:id' => 'users#remove_admin', as: :remove_admin
  root 'movies#index'
  get 'books#index'=> 'books#index', as: :root1
  delete '/movies/:movie_id/favorites/:id' => 'favorites#destroy', as: :movie_favorite
  resources :books
  resources :movies  do
     resources :reviews
     resources :favorites
   end
  # get 'movies'=>'movies#index', as: :index
  # get 'movies/new'=>"movies#new"
  # get 'movies/:id'=>'movies#show', as: :movie
  # get 'movies/:id/edit'=>'movies#edit', as: "edit_movie"
  # patch 'movies/:id'=>'movies#update'	

end

app/models/user.rb
class User < ApplicationRecord
      has_secure_password
      has_many :reviews
      has_many :favorites,dependent: :destroy
      has_many :favorite_movies, through: :favorites,source: :movie
     validates :name, presence: true
    validates :email, presence: true,
                    format: /\w+@\w+\.{1}[a-zA-Z]{2,}/ ,
                    uniqueness: {
                            case_sensitive: false
                            }
     validates :password, :length => {:within => 6..15, allow_blank: true}
    include Gravtastic
  		gravtastic
    def self.authenticate?(email,password)
        user = User.find_by(email:email)
        if user and user.authenticate(password)
          true
        else
          false
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
before_action :require_signin, only: [:show, :edit, :update, :destroy]
before_action :check_current_user, only: [:edit, :update, :destroy]
before_action :require_signout,only:[:new]
  def index
    @users=User.all 
  end
   def show
    @user=User.find(params[:id])
    # @fav_movies=@user.favorite_movies
  end
  def new
    @user=User.new
  end
   def edit
    # @user=User.find(params[:id])  
  end
  def update
    # @user=User.find(params[:id])  
    if @user.update(user_params)
      flash[:notice]="successfully updated!!"
       redirect_to users_path
    else
        render :edit
      end
  end

  def create
    @user=User.create(user_params)
    if @user.save
      UserMailer.welcome_email(@user).deliver
      session[:user_id]=@user.id
      flash[:notice]="successfully Registered!! Welcome #{@user.name}"
       redirect_to user_path(@user)
    else
      render :new
    end
  end

  def destroy
    @user.delete
    redirect_to users_path(@user),notice: "One User is deleted!!"
  end

  def create_admin
    @user=User.find(params[:id])
    @user.admin= true
    @user.save
    flash[:notice]="Admin successfully created!!"
    redirect_to user_path(@user)
  end

  def remove_admin
    @user=User.find(params[:id])
    @user.admin= false
    @user.save
    flash[:notice]="Admin successfully Removed!!"
    redirect_to user_path(@user)
  end

  private
    def user_params
      params.require(:user).permit!
    end

  def check_current_user
    @user = User.find(params[:id])
    unless current_user == @user || current_user.admin
      flash[:error] = "you are not allow for this action"
      redirect_to user_path(@user)
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
	def user_gravatar(user,options={})
		size=options[:size] || 80
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "http://secure.gravatar.com/avatar/#{gravatar_id}s=#{size}"
    image_tag(gravatar_url, alt: user.name)
  end
end

app/views/users/_form.html.erb
<%= render 'shared/errors', object: @user%>


<%= form_for @user do |f| %>
<center>

<table>
	<tr>
		<td>
			<%= f.label:Name %></td>
			<td><%= f.text_field:name, :autofocus=>true %>
		</td>
	</tr>
	<tr>
		<td>
			<%= f.label:Email %></td>
			<td>
			<%= f.email_field:email  %>
		</td>
	</tr>
	<tr>
		<td>
			<%= f.label:password %></td>
			<td>
			<%= f.password_field:password%>
		</td>
	</tr>
	<tr>
		<td>
			<%= f.label:confirm_password %></td>
			<td>
			<%= f.password_field:password_confirmation%>
		</td>
	</tr>
	
	<tr><td></td><td> <%= link_to "Cancel", users_path, class: 'btn btn-primary' %>
		<% if @user.new_record? %>
			<%= f.submit "Sing Up"%>
			<%else%>
			<%= f.submit "Update"%>
			<%end%>
			 </td> </tr>
</table>
</center>
<%end%>

app/views/users/edit.html.erb
<center>
<h1 style="background-color: #52a6bf">Update Existing Users Here!</h1>
</center>
<%= content_for :page_title, "New "%>
<%= render 'form'%>

app/views/users/index.html.erb
<h1><%= pluralize(@users.count,'user')%></h1>
<%= link_to("Add user",new_user_path)%><br>

<table class="table" >
	<tr> 
	<thead class="thead-dark">
		<th>#</th> 
		<th>Name</th>
		<th>Email</th> 
		<th></th>
		<th>Actions</th>
		<th></th>
	</thead>
</tr>
	<%count=1 %>
	<%@users.each do |user|%>
	<tr>
		<td><%= count%></td>
		<td><%= link_to(user.name,user_path(user.id))%> </td>
		<td><%= user.email%></td>
		<td>	<% if current_user && current_user.sadmin? %>
			<% unless user.admin? %>
			<%= link_to("Make admin",create_admin_path(user),  class: "btn btn-primary"  )%>
			<%else%>
				<%= link_to("Remove admin",remove_admin_path(user),  class: "btn btn-primary")%>
			<%end%>
			<%end%>
		</td>
		
		<% if current_user && current_user.admin? %>
		<td><%= link_to("Edit Account",edit_user_path(user),  class: "btn btn-primary"  )%></td>
		<td><%= link_to("Delete Account",users_path(user),  class: "btn btn-danger"  , method: :delete, data:{confirm:"Are you sure"})%></td>
		<%end%>
	</tr>
	<%count+=1%>
	<%end%>
</table>

app/views/users/new.html.erb
<center>
<h1 style="background-color: #52a6bf">Insert New Users Here!</h1>
</center>
<%= content_for :page_title, "New "%>
<%= render 'form'%>

app/views/users/show.html.erb
<div class="main">
					
<table class="table">
	<tr>
		<td>NAME:</td>
		<td><%= @user.name%></td>
	</tr>
	<tr>
		<td>Email:</td>
		<td><%= @user.email%></td>
		
	</tr>
	<tr>
		<td>Member Since:</td>
		<td><%= @user.created_at.strftime("%B %Y")%></td>
		
	</tr>
	<tr>
		<td></td>
		<% if current_user.admin?%>
		<td><%= link_to("Delete Account",users_path(@user),  class: "btn btn-danger"  , method: :delete, data:{confirm:"Are you sure"})%></td>
		<%end%>
	</tr>
	
	<%= link_to("Back","/users")%>
	</table>
</div>

	
<div style="width: 500px; float:left; height:300px; background:gray; margin:10px; overflow: scroll">	
	<h1>Reviews</h1>
<ol>
    <% @user.reviews.each do |review| %>
    <li>
        <ul>
            <li>  Movie : <%= link_to Movie.find(review.movie_id).title, movie_path(review.movie_id) %> 
		<%= user_gravatar @user %>
	</li> <br>
            <li>Stars : <%= pluralize(review.stars,'star')%></li> <br>
            <li>Time: <%= time_ago_in_words(review.updated_at) %> ago </li><br>
            <li>Comment : <%= review.comment %></li>
        </ul>
    </li>
    <% end %>
</ol>
</div>

<div style="width: 500px; float:right; height:300px; background:gray; margin:10px; overflow: scroll">
<h1>List of favorite movies</h1>
<ol>
    <% @user.favorite_movies.each do |favorite| %>
    <li>
        <ul>
            <li>  Movie : <%= link_to Movie.find(favorite.id).title, movie_path(favorite.id) %> 
		
	</li> <br>
                        
        </ul>
    </li>
    <% end %>
</ol>
</div>