config/routes.rb
Rails.application.routes.draw do
  
  
 
  
  resources :genres
  resource :sessions,only: [:new,:create,:destroy]
  resources :users
  get 'create_admin/:id' => 'users#create_admin', as: :create_admin
  get 'remove_admin/:id' => 'users#remove_admin', as: :remove_admin
  root 'movies#index'
  get 'books#index'=> 'books#index', as: :root1
  delete '/movies/:movie_id/favorites/:id' => 'favorites#destroy', as: :movie_favorite
  resources :books
  resources :movies  do
     resources :reviews
     resources :favorites
   end
  # get 'movies'=>'movies#index', as: :index
  # get 'movies/new'=>"movies#new"
  # get 'movies/:id'=>'movies#show', as: :movie
  # get 'movies/:id/edit'=>'movies#edit', as: "edit_movie"
  # patch 'movies/:id'=>'movies#update'	

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :set_movie
  before_action :require_signin
  
  def index
    @reviews = @movie.reviews
  end

  def new
    @review = @movie.reviews.new
  end

  def create
    @review = @movie.reviews.new(review_params)
    @review.user=current_user
    if !check_user_review_for_movie && @review.save
      redirect_to movie_reviews_path(@movie),
                    notice: "Thanks for your review!"
    else
      flash[:alert] = "You already give the review for this movie"
      render :new
    end
  end
  
 def edit
   @review = @movie.reviews.find(params[:id])
 end

  def update
      @review = @movie.reviews.find(params[:id])

     if @review.update(review_params)
        flash[:success] = "movie updated"
      redirect_to movie_reviews_path(@movie),notice: "One review is Updated!!"
    else
      render :edit
    end
  end
   def destroy
    @movie.reviews.find(params[:id]).destroy
    redirect_to movie_reviews_path(@movie),notice: "One review is deleted!!"
  end
private

  def review_params
    params.require(:review).permit(:comment, :stars)
  end

  def set_movie
    @movie = Movie.find(params[:movie_id])
  end

  def check_user_review_for_movie
    @movie.reviews.each do |review|
      if review.user_id == current_user.id
        return true
      end
    end
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
	def format_average_stars(movie)
		if movie.average_stars.nil?
			content_tag(:strong, "No Review")
		else
			str= '*' * movie.average_stars.to_i
			str+" "+pluralize(number_with_precision(movie.average_stars, :precision=>1),' star')
			end			
	end
end

app/views/reviews/_form.html.erb
<%= form_for [@movie, @review] do |f| %>
  <%= render "shared/errors", object: @review %>
  <fieldset>
    <ol>
      <li class="required stars">
        <%= f.label :stars %>
          <span class="star">
           
              <%= f.select:stars,Review::STARS,prompt: ":-select-:"%>
        </span>   
      </li>
      <li class="required">
        <%= f.label :comment %>
        <%= f.text_area :comment, cols: 80, placeholder: "What did you think?" %>
      </li>
    </ol>
    <p>
      <%= f.submit 'Post Review' %> 
      <%= link_to "Cancel", @movie, class: 'button' %>
    </p>
  </fieldset>
<% end %>

app/views/reviews/edit.html.erb
<header id="content-header">
  <h1>Update Review of <%= link_to @movie.title, @movie %></h2>
</header>
<%= render 'form'%>

app/views/reviews/index.html.erb
<header id="content-header">
  <h1>Reviews for <%= link_to(@movie.title, @movie) %></h2>
</header>

<ol id="reviews">
  <% @reviews.each do |review| %>
    <li>
      <span class="review"><%= pluralize(review.stars, 'star') %></span> given by
      <span> <%= link_to review.user.name,user_path(review.user.id)%></span>
      <span class="date"><%= time_ago_in_words(review.created_at) %> ago</span>
      <p>
        &quot;<%= review.comment %>&quot;
      </p>
      <%= link_to("Delete",[@movie, review],  class: "btn btn-danger"  , method: :delete, data:{confirm:"Are you sure"})%>
      <%= link_to("Edit",edit_movie_review_path(@movie.id,review.id),  class: "btn btn-primary")%>
    </li>
  <% end %>
</ol>

app/views/reviews/new.html.erb
<header id="content-header">
  <h1>New Review for <%= link_to @movie.title, @movie %></h2>
</header>

<%= form_for [@movie, @review] do |f| %>
  <%= render "shared/errors", object: @review %>
  <fieldset>
    <ol>
      <li class="required stars">
        <%= f.label :stars %>
          <span class="star">
           
              <%= f.select:stars,Review::STARS,prompt: ":-select-:"%>
        </span>   
      </li>
      <li class="required">
        <%= f.label :comment %>
        <%= f.text_area :comment, cols: 80, placeholder: "What did you think?" %>
      </li>
    </ol>
    <p>
      <%= f.submit 'Post Review' %> 
      <%= link_to "Cancel", @movie, class: 'button' %>
    </p>
  </fieldset>
<% end %>