config/routes.rb
Rails.application.routes.draw do
  
  
 
  
  resources :genres
  resource :sessions,only: [:new,:create,:destroy]
  resources :users
  get 'create_admin/:id' => 'users#create_admin', as: :create_admin
  get 'remove_admin/:id' => 'users#remove_admin', as: :remove_admin
  root 'movies#index'
  get 'books#index'=> 'books#index', as: :root1
  delete '/movies/:movie_id/favorites/:id' => 'favorites#destroy', as: :movie_favorite
  resources :books
  resources :movies  do
     resources :reviews
     resources :favorites
   end
  # get 'movies'=>'movies#index', as: :index
  # get 'movies/new'=>"movies#new"
  # get 'movies/:id'=>'movies#show', as: :movie
  # get 'movies/:id/edit'=>'movies#edit', as: "edit_movie"
  # patch 'movies/:id'=>'movies#update'	

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/characterization.rb
class Characterization < ApplicationRecord
  belongs_to :movie
  belongs_to :genre
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :movie
  belongs_to :user
end

app/models/genre.rb
class Genre < ApplicationRecord
validates :name, presence: true, 
						uniqueness: {
                            case_sensitive: false
                            }
     has_many :characterizations
     has_many :movies, through: :characterizations 
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many_attached :uploads
  has_many :reviews,dependent: :destroy
  has_many :favorites,dependent: :destroy
  has_many :fans, through: :favorites, source: :user

  has_many :characterizations
  has_many :genres, through: :characterizations
  validates :title, presence: true
    validates :released_on, presence: true
    validates :duration, presence: true
    validates :description, length: { minimum: 25 }
    validates :total_gross, :numericality => { :greater_than_or_equal_to => 0 }
    # validates :image_file_name, allow_blank: true,format:{
    #     with: /\w+\.(gif|jpg|png)\z/i,
    #     message: "must reference a GIF, JPG, or PNG "
    # }
    RATINGS = %w(G PG PG-13 R NC-17)
  def flop?
    total_gross<50000000
  end
  def self.released
    where("released_on <?",Time.now).order(released_on: :desc)
  end

  def average_stars
    reviews.average(:stars)
  end

  def self.recent_reviews(movie)
    movie.reviews.order(updated_at: :desc).limit(2)
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :movie
  belongs_to :user
  
    #validates :released_on, presence: true
   #validates :stars, :numericality => { :greater_than_or_equal_to => 1,:less_than_or_equal_to => 5 }

STARS = [1, 2, 3, 4, 5]

  validates :stars, inclusion: {
    in: STARS,
    message: "must be between 1 and 5"
  }
  
    validates :comment, length: { minimum: 4 }
end

app/models/session.rb
class Session < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
      has_secure_password
      has_many :reviews
      has_many :favorites,dependent: :destroy
      has_many :favorite_movies, through: :favorites,source: :movie
     validates :name, presence: true
    validates :email, presence: true,
                    format: /\w+@\w+\.{1}[a-zA-Z]{2,}/ ,
                    uniqueness: {
                            case_sensitive: false
                            }
     validates :password, :length => {:within => 6..15, allow_blank: true}
    include Gravtastic
  		gravtastic
    def self.authenticate?(email,password)
        user = User.find_by(email:email)
        if user and user.authenticate(password)
          true
        else
          false
    end
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books=Book.all
  end

  def show
    @book=Book.find(params[:id])
  end

  def edit
    @book=Book.find(params[:id])
  end

  def update
    book=Book.find(params[:id]) 
    book.update(book_params)
    redirect_to book_path
  end

  def new
   @book=Book.new
  end

  def create
    @book=Book.create(book_params)
    redirect_to book_path(@book)
  end

  def destroy
    @book=Book.find(params[:id]).delete
    redirect_to books_path(@book)
  end

  private
  def book_params
    params.require(:book).permit!
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
before_action :require_signin, only: [:show, :edit, :update, :destroy]
before_action :check_current_user, only: [:edit, :update, :destroy]
before_action :require_signout,only:[:new]
  def index
    @users=User.all 
  end
   def show
    @user=User.find(params[:id])
    # @fav_movies=@user.favorite_movies
  end
  def new
    @user=User.new
  end
   def edit
    # @user=User.find(params[:id])  
  end
  def update
    # @user=User.find(params[:id])  
    if @user.update(user_params)
      flash[:notice]="successfully updated!!"
       redirect_to users_path
    else
        render :edit
      end
  end

  def create
    @user=User.create(user_params)
    if @user.save
      UserMailer.welcome_email(@user).deliver
      session[:user_id]=@user.id
      flash[:notice]="successfully Registered!! Welcome #{@user.name}"
       redirect_to user_path(@user)
    else
      render :new
    end
  end

  def destroy
    @user.delete
    redirect_to users_path(@user),notice: "One User is deleted!!"
  end

  def create_admin
    @user=User.find(params[:id])
    @user.admin= true
    @user.save
    flash[:notice]="Admin successfully created!!"
    redirect_to user_path(@user)
  end

  def remove_admin
    @user=User.find(params[:id])
    @user.admin= false
    @user.save
    flash[:notice]="Admin successfully Removed!!"
    redirect_to user_path(@user)
  end

  private
    def user_params
      params.require(:user).permit!
    end

  def check_current_user
    @user = User.find(params[:id])
    unless current_user == @user || current_user.admin
      flash[:error] = "you are not allow for this action"
      redirect_to user_path(@user)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def current_user?(user)
	  		current_user==user
	 end
	 
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
	def formate_total_gross(movie)
		if movie.flop?
			#"<strong>Flop</strong>".html_safe
			 content_tag(:strong, 'Flop!')
		else
			content_tag(:strong, 'Hit!')
		end
	end
	
	
	# def image_for(movie)
	# 		    if movie.image_file_name.blank?
 #      image_tag('placeholder.png')
 #    else
 #      image_tag(movie.image_file_name)
 #    end
 
			# img=movie.image_file_name
		# if File.exist?("Rails.root/'app'/'assets'/'images'/#{img}")
		# 	image_tag(movie.image_file_name)
		# else
		# 	image_tag 'placeholder.png'
		# end
	# end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
	def format_average_stars(movie)
		if movie.average_stars.nil?
			content_tag(:strong, "No Review")
		else
			str= '*' * movie.average_stars.to_i
			str+" "+pluralize(number_with_precision(movie.average_stars, :precision=>1),' star')
			end			
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def user_gravatar(user,options={})
		size=options[:size] || 80
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "http://secure.gravatar.com/avatar/#{gravatar_id}s=#{size}"
    image_tag(gravatar_url, alt: user.name)
  end
end

app/views/layouts/_footer.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<footer class="footer navbar-static-bottom" style="background-color: #012e30">
<center>
	<a href="#" class="fa fa-facebook"></a>
	<a href="#" class="fa fa-twitter"></a>
	<a href="#" class="fa fa-google"></a>
	<a href="#" class="fa fa-linkedin"></a>
	<a href="#" class="fa fa-instagram"></a>
	<a href="#" class="fa fa-youtube"></a>
</center>
</footer>

app/views/layouts/_header.html.erb
 <nav class="navbar navbar-inverse navbar-static-top" style="background-color: #789485" >
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to 'FLIX',root_path, class: "navbar-brand"%>
    </div>
    <button class = "navbar-toggle" data-toggle = "collapse" data-target = "#navHeaderCollapse">
                <span class = "icon-bar"></span>
                <span class = "icon-bar"></span>
                <span class = "icon-bar"></span>
            </button>
    <ul class="nav navbar-nav" style="color: black">
      <li class="active"><%= link_to'Home',root_path%></li>
      <li><%= link_to'Users',users_path%></li>
      <li><a href="#">Page 2</a></li>
    </ul>
    
    <ul class="nav navbar-nav navbar-right">
      <% if session[:user_id]%>
         <li> <%= User.find(session[:user_id]).name%></li>
    <%else%>
      <li><%= link_to'Sign Up',users_path,class: "glyphicon glyphicon-user"%></li>
      <<li><%= link_to'Sign In',new_sessions_path,class: "glyphicon glyphicon-user"%></li>
      <%end%>
    </ul>

  </div>
</nav> 

app/views/layouts/_sidebar.html.erb
<div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Flix" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>
   
  </head>
  <body>
   <%= nav_bar static: :top, brand: "FLIX", responsive: true do %>
    <%= menu_group do %>
        <%= menu_item "Home", root_path %>
        <%= menu_divider %>
       
        <%= menu_item "Users", users_path %>
        <%= menu_item "Contact", "" %>
    <% end %>
             

         <%= menu_group pull: :right do %>
        <% if current_user %>

            <%= menu_item current_user.name, user_path(current_user.id)%>
            <%= menu_item "Log Out", sessions_path, method: :delete %>
        <% else %>
            <%= menu_item "Sign In", new_sessions_path %>
            <%= menu_item "Sign Up", new_user_path %>
           
        <% end %>
    <% end %>
    <% end %>
        </div>
      </div>
    </div>
  
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
       </div>
         
    </div> <!-- /container -->
  
<%= render 'layouts/footer'%>

  </body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
<section id="errors">
  <header>
    <h2>
      Oops! The <%= object.class.name.humanize.downcase %> could not be saved. 
    </h2>
    <h3>
      Please correct the following <%= pluralize(object.errors.count, "error") %>:
    </h3>
  </header>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</section>
<% end %>